### ISSUE TITLE
Core WCM RTE inline plugin toolbars not displayed

### ISSUE THREAD

**Issue by shravanthprasad** [adobe/aem-core-forms-components#1374] opened 2024-09-05 06:40 UTC
We see an issue with RTE inline toolbars not displayed for core wcm rich text component.
Analysis:
The JS below with af-apps pkg is causing this issue-
/apps/core/fd/components/form/container/v2/container/clientlibs/editorhook/js/toolbaractionhook.js

```
if(!(hasRichTextLabel || hasRichTextAttribute)){
                editable.config.editConfig.inplaceEditingConfig.editorType="plaintext";
            }
```
AEM version 6.5.20
core components version 2.24.2
core forms components version 1.1.39-enumB004

**Comment by shravanthprasad** [comment] 2024-09-05 06:48
Example page after installing examples pkg - Toolbar not visible
<img width="711" alt="image" src="https://github.com/user-attachments/assets/53c45536-5386-4c12-9c74-83bc86371254">
After deleting the toolbaractionhook.js and invalidating cache - Toolbar is visible
<img width="665" alt="image" src="https://github.com/user-attachments/assets/d8416286-6e6e-4622-85a8-72503fba1653">

**Comment by rismehta** [comment] 2024-09-06 09:22
Duplicate of, https://github.com/adobe/aem-core-forms-components/issues/1371. Closing this

**Closed by rismehta** 2024-09-06 09:22 UTC

**Comment by shravanthprasad** [comment] 2024-09-09 10:45
@rismehta  - Thanks for the quick fix. Can you please provide a release(1.1.39-enumB004) with the below fixes on top of the as we have just upgraded our aem version
(https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-1.1.39-enumB004)
Fixes:
1)https://github.com/adobe/aem-core-forms-components/pull/1326 - conflicting vault filter
2)https://github.com/adobe/aem-core-forms-components/pull/1376 - rte fix for wcm

**Comment by shravanthprasad** [comment] 2024-09-11 01:26
> > Can you please provide a release(1.1.39-enumB004) with the below fixes on top of the as we have just upgraded our aem version
> > (https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-1.1.39-enumB004)
> > Fixes:
> > 1)#1326 - conflicting vault filter
> > 2)#1376 - rte fix for wcm
> 
> Could you please submit a customer request for this through the support channel ?

Hi @rismehta  - Support ticket - E-001352137
Thanks

**Comment by shravanthprasad** [comment] 2024-09-12 03:45
@rismehta - Update to this request, the following issues are also reported on our Prod and need it to be added to the release 
[-](https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-1.1.39-enumB004)
-
https://github.com/adobe/aem-core-forms-components/pull/1326
https://github.com/adobe/aem-core-forms-components/pull/1225
https://github.com/adobe/aem-core-forms-components/pull/1321
https://github.com/adobe/aem-core-forms-components/pull/1376

**Comment by rismehta** [comment] 2024-09-12 09:37
@shravanthprasad We are currently backporting the latest changes from the master branch to the release/650 branch through this PR, https://github.com/adobe/aem-core-forms-components/pull/1391. After merging, we will proceed with creating a hotfix. Please note that this process may take some time.

**Comment by barshat7** [comment] 2024-09-13 12:31
We have released the hotfix
https://github.com/adobe/aem-core-forms-components/releases/tag/core-forms-components-reactor-1.1.39-enumB010

**Comment by shravanthprasad** [comment] 2024-09-17 03:39
@barshat7  - I verified all the fixes and they are working fine with this release. Thank you!
