### ISSUE TITLE
Adaptive Form Core Components needs to use accordion layout for dialogs instead of tab layout

### ISSUE THREAD

**Issue by rakhi4110** [adobe/aem-core-forms-components#521] opened 2023-03-01 22:45 UTC
### Expected Behaviour
Adaptive Forms uses a sidebar to display the component dialog instead of opening it in a modal/popup window like Sites components. Due to this, the component dialog needs to use the accordion layout to display correctly in the Sidebar.
An example of the foundation adaptive forms dialog shown below
![Accordion layout in AF](https://user-images.githubusercontent.com/34041259/222281886-6c098e63-f522-4601-b7e0-1c5cd41392f6.png)

### Actual Behaviour
Due to tabbed layout used, the dialog appears broken. Screenshot below
![Tabbed layout in AF](https://user-images.githubusercontent.com/34041259/222281833-61ca2929-2edb-4b69-adc8-455eeeef469e.png)

#### Steps to Reproduce
1. Download and install the latest version of AEM cloud sdk in your local machine.
2. Install the Forms feature pack as documented [here](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/forms/setup-configure-migrate/setup-local-development-environment.html?lang=en#add-forms-archive-configure-users).
3. Create a new maven project using the latest archetype including examples and headless forms.
4. Deploy the project to the local AEM instance. 
5. Create a new Adaptive form using the Adaptive Forms (Core Components) template.
6. Drag and drop Core components into the form and edit them to bring up the dialog in the sidebar.

#### Platform and Version
Local machine - MacBook Pro with Apple Silicon
OS - macOS Ventura 13.2.1
Java - Open JDK 11

#### Logs taken while reproducing problem

**Comment by nit23uec** [comment] 2023-03-02 05:43
Core Components are currently part of pre-release. 
When launching the SDK Quickstart, include the argument `-r prerelease`.

**Comment by rakhi4110** [comment] 2023-03-02 22:05
The `-r prerelease` argument doesn't change anything in the behaviour of the form. The issue still exists.

Wasn't aware that this is pre-release as the [official documentation](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/forms/adaptive-forms-authoring/authoring-adaptive-forms-core-components/create-an-adaptive-form-on-forms-cs/creating-adaptive-form-core-components.html?lang=en) doesn't mention them as pre-release and recommends using these for new forms.

**Comment by nit23uec** [comment] 2023-03-03 05:28
@rakhi4110 , can you please share exact the AEM Cloud SDK version you are using? It will help us debugging this issue. Thanks!

**Comment by rismehta** [comment] 2023-04-10 10:55
@rakhi4110 Please make use of the latest released quickstart, since core component feature toggle was added to pre-release recently.

**Comment by vabs95** [comment] 2023-04-10 11:23
@rismehta I'm also facing the same issue , I followed the below documentation to setup Forms Core

https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/forms/setup-configure-migrate/setup-local-development-environment.html?lang=en#enable-adaptive-forms-core-components-for-an-existing-aem-archetype-based-project

Version used
AEM SDK : 2023.3.11382.20230315T073850Z-230100
AEM Forms SDK: 2023.02.01.00-230100
AEM Forms Core: 2.0.8

**Comment by rismehta** [comment] 2023-04-14 11:18
> I'm also facing the same issue , I followed the below documentation to setup Forms Core

Please enable the pre-release option as described here, https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/release-notes/prerelease.html?lang=en#local-sdk

**Comment by rismehta** [comment] 2023-04-14 11:19
Core components is part of release as part of the following AEM SDK,

2023.3.11382.20230315T073850Z-230200

**Comment by rismehta** [comment] 2023-04-14 11:20
Please confirm if the issue is resolved, so that it can be closed

**Comment by vabs95** [comment] 2023-04-17 10:59
@rismehta The issues seems to resolved in the new SDK, thanks. Now it opens as a Modal same as Core Sites Components.

**Comment by rismehta** [comment] 2023-04-18 09:20
Thanks. Closing the issue

**Closed by rismehta** 2023-04-18 09:20 UTC
